"""PR Manager module for creating, updating, and preserving evidence in Pull Requests."""

from codegraph.git.models import PullRequestPlan
from codegraph.github.client import GitHubClient
from codegraph.github.models import PRMetadata


class PRManager:
    """Manages creation, updates, and evidence provenance formatting for GitHub Pull Requests."""

    def __init__(self, client: GitHubClient) -> None:
        self.client = client

    def create_or_update_pr(
        self,
        repo: str,
        plan: PullRequestPlan,
        existing_pr_number: int | None = None,
    ) -> tuple[PRMetadata | None, str | None]:
        """Create a new PR or update an existing open PR while preserving evidence provenance."""
        formatted_body = self._format_pr_body_with_evidence(plan)

        if existing_pr_number:
            try:
                updated = self.client.update_pull_request(
                    repo=repo,
                    pr_number=existing_pr_number,
                    title=plan.title,
                    body=formatted_body,
                )
                return updated, None
            except Exception as e:
                return None, f"Failed to update existing PR #{existing_pr_number}: {e}"

        try:
            created = self.client.create_pull_request(
                repo=repo,
                title=plan.title,
                body=formatted_body,
                head_branch=plan.branch,
                base_branch=plan.base_branch,
            )
            return created, None
        except Exception as e:
            return None, f"Failed to create new Pull Request: {e}"

    def _format_pr_body_with_evidence(self, plan: PullRequestPlan) -> str:
        """Construct a markdown PR body preserving investigation, repair, and test evidence."""
        lines = [
            "## Summary",
            plan.summary,
            "",
            "## Problem Description",
            plan.problem,
            "",
            "## Root Cause Analysis",
            plan.root_cause,
            "",
            "## Key Changes",
        ]
        for c in plan.changes:
            lines.append(f"- {c}")

        lines.extend([
            "",
            "## Test Verification",
            plan.tests,
            "",
            "## Risk Assessment",
            plan.risks,
            "",
            "## Evidence Provenance",
        ])
        for ev in plan.evidence:
            lines.append(f"- [{ev}] Grounded codebase evidence reference")

        lines.extend([
            "",
            "---",
            "*Generated by CodeGraph RAG — Code Intelligence & Automated Repair System*",
        ])

        return "\n".join(lines)
